### ISSUE TITLE
gron

### ISSUE THREAD

**Issue by easrng** [terinjokes/human-intermediate-formats#1]
Gron is a tool that turns JSON into a line based format that's technically a JS subset and is easier to use with tools like grep.
It's output looks like this:
```js
json = {};
json.contact = {};
json.contact.email = "mail@tomnomnom.com";
json.contact.twitter = "@TomNomNom";
json.github = "https://github.com/tomnomnom/";
json.likes = [];
json.likes[0] = "code";
json.likes[1] = "cheese";
json.likes[2] = "meat";
json.name = "Tom";
```
I'd send a PR, but I'm not sure it quite fits with this list, so I thought I'd ask here.
The link to its repo is https://github.com/TomNomNom/gron.

**Comment by terinjokes** [comment]
Oh this is an interesting project! Adding it to my computer now.

I hadn't considered tools that transform other plaintext formats for this list, but I'd definitely consider it. I'll have a think and get back to you.
